MyUFC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('luchadores/', include(('luchadores.urls', 'luchadores'), namespace='luchadores')),
    path('combates/', include(('combates.urls', 'combates'), namespace='combates')),
    
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from bases.views import Home

urlpatterns = [
    path('', Home.as_view(), name='home'),
    
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

combates/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from combates.views import CombateListView, CombateEditView, CombateDeleteView, CombateCreateView, CombateDetailView

urlpatterns = [
    path('', CombateListView.as_view(), name='combates-list'),
    path('new', CombateCreateView.as_view(), name = 'combates_create'),
    path('edit/<uuid:pk>/', CombateEditView.as_view(), name = 'combates_edit'),
    path('delete/<uuid:pk>/', CombateDeleteView.as_view(), name='combates_delete'),
    path('detail/<uuid:pk>/', CombateDetailView.as_view(), name='combates_detail'),
]

luchadores/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from luchadores.views import luchadoresList, LuchadorCreateView, LuchadorEditView, LuchadorDeleteView, LuchadorDetailView

urlpatterns = [
    path('', luchadoresList.as_view(), name='luchadores-list'),
    path('new', LuchadorCreateView.as_view(), name = 'luchadores_create'),
    path('edit/<uuid:pk>/', LuchadorEditView.as_view(), name = 'luchadores_edit'),
    path('delete/<uuid:pk>/', LuchadorDeleteView.as_view(), name='luchadores_delete'),
    path('detail/<uuid:pk>/', LuchadorDetailView.as_view(), name='luchadores_detail'),
]

templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="icon" href="{% static 'base/img/logoMyUFC.png' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
        {% block import_css %}{% endblock import_css %}
    </head>
    <body>
        {% block menu %}
        <div class="row">
            <div class="menu fixed-top col-lg-6 col-md-10 col-sm-10 mt-4 m-auto">
                <div class="row h-100">
                    <a class="col-lg-4 col-md-12 col-sm-12 pt-2 pb-2 text-center menuLink2" href="{% url 'luchadores:luchadores-list' %}">LUCHADORES</a>
                    <a class="col-lg-4 col-md-12 col-sm-12 text-center mma menuLink1" href="{% url 'bases:home' %}">my ufc</a>
                    <a class="col-lg-4 col-md-12 col-sm-12 pt-2 pb-2 text-center menuLink2" href="{% url 'combates:combates-list' %}">COMBATES</a>
                </div>
            </div>
        </div>
        {% endblock menu %}



        {% block content %}

        {% endblock content %}



        {% block footer %}
            {% comment %} <a class = "logout col-1 m-auto bg-black text-light" href="{% url 'bases:logout' %}"><ion-icon name="log-out-outline"></ion-icon></a> {% endcomment %}


    <footer class="text-white text-center text-lg-start bg-dark">
      <!-- Grid container -->
      <div class="container p-4">
        <!--Grid row-->
        <div class="row mt-4">
          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
            <h5 class="text-uppercase mb-4">Aviso legal</h5>
  
            <p class = "linkFooter">
                Esta página web ha sido creada con fines académicos como proyecto de fin de grado.
            </p>
  
            <p class = "linkFooter">
                Cualquier información proporcionada será utilizada únicamente para fines educativos y no será compartida con terceros.
            </p>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase mb-4">Contacto</h5>
  
            <ul class="fa-ul" style="margin-left: 1.65em;">
              <li class="mb-3">
                <a class = "linkFooter" href="mailto:castrilloredondovictor@gmail.com" target="_blank"><span class="fa-li"><ion-icon name="folder-open-outline"></ion-icon></span><span class="ms-2">castrilloredondovictor@gmail.com</span></a>
              </li>
              <li class="mb-3">
                <a class = "linkFooter" href="https://www.instagram.com/viictor.cr/" target="_blank"><span class="fa-li"><ion-icon name="logo-instagram"></ion-icon></span><span class="ms-2">@viictor.cr</span></a>
              </li>
              <li class="mb-3">
                <a class = "linkFooter" href="tel:+34665818706"><span class="fa-li"><ion-icon name="call-outline"></ion-icon></span><span class="ms-2">+34 665 818 706</span></a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase mb-4">Acciones</h5>
  
            <ul class="fa-ul" style="margin-left: 1.65em;">
                <li class="mb-3">
                    <a class = "linkFooter" href="{% url 'bases:home' %}"><span class="fa-li"><ion-icon name="apps-outline"></ion-icon></span><span class="ms-2">Inicio</span></a>
                  </li>
                  <li class="mb-3">
                    <a class = "linkFooter" href="#" class="irArriba"><span class="fa-li"><ion-icon name="arrow-up-outline"></ion-icon></span><span class="ms-2">Volver</span></a>
                  </li>
              <li class="mb-3">
                <a class = "linkFooter" href="{% url 'bases:logout' %}"><span class="fa-li"><ion-icon name="log-out-outline"></ion-icon></span><span class="ms-2">Log out</span></a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
      <!-- Grid container -->
  
      <!-- Copyright -->
      <div class = "row" style="background-color: rgba(0, 0, 0, 0.2);">
        
          <div class="text-center p-3 col-lg-6 col-md-6 col-sm-12">
            Usuario:
            <a class="linkFooter" href="/admin" target="_blank">{{user}}</a>
          </div>
          <div class="text-center p-3 col-lg-6 col-md-6 col-sm-12">
            © 2023 Copyright:
            <a class="linkFooter" href="https://www.ufc.com/" target="_blank">ufc.com</a>
          </div>
      </div>
      <!-- Copyright -->
    </footer>
        {% endblock footer %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

        <script>
            $(document).ready(function(){

                $('.ir-arriba').click(function(){
                    $('body, html').animate({
                        scrollTop: '0px'
                    }, 5000);
                });
            
                $(window).scroll(function(){
                    if( $(this).scrollTop() > 0 ){
                        $('.ir-arriba').slideDown(5000);
                    } else {
                        $('.ir-arriba').slideUp(5000);
                    }
                });
            
            });
        </script>
        
        {% block javascript %}
        
        {% endblock javascript %}

    </body>
</html>