MyUFC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('luchadores/', include(('luchadores.urls', 'luchadores'), namespace='luchadores')),
    path('combates/', include(('combates.urls', 'combates'), namespace='combates')),
    
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from bases.views import Home

urlpatterns = [
    path('', Home.as_view(), name='home'),
    
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

combates/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from combates.views import CombateListView, CombateEditView, CombateDeleteView, CombateCreateView, CombateDetailView

urlpatterns = [
    path('', CombateListView.as_view(), name='combates-list'),
    path('new', CombateCreateView.as_view(), name = 'combates_create'),
    path('edit/<uuid:pk>/', CombateEditView.as_view(), name = 'combates_edit'),
    path('delete/<uuid:pk>/', CombateDeleteView.as_view(), name='combates_delete'),
    path('detail/<uuid:pk>/', CombateDetailView.as_view(), name='combates_detail'),
]

luchadores/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from luchadores.views import luchadoresList, LuchadorCreateView, LuchadorEditView, LuchadorDeleteView, LuchadorDetailView

urlpatterns = [
    path('', luchadoresList.as_view(), name='luchadores-list'),
    path('new', LuchadorCreateView.as_view(), name = 'luchadores_create'),
    path('edit/<uuid:pk>/', LuchadorEditView.as_view(), name = 'luchadores_edit'),
    path('delete/<uuid:pk>/', LuchadorDeleteView.as_view(), name='luchadores_delete'),
    path('detail/<uuid:pk>/', LuchadorDetailView.as_view(), name='luchadores_detail'),
]

luchadores/models.py
from django.db import models
from bases.models import BaseModel


GUARDIA_CHOICES = [
        ('Diestra', 'Diestra'),
        ('Zurda', 'Zurda'),
]

PAISES_CHOICES = [
    ('afghanistan', 'Afganistán'),
    ('albania', 'Albania'),
    ('algeria', 'Argelia'),
    ('andorra', 'Andorra'),
    ('angola', 'Angola'),
    ('antigua_and_barbuda', 'Antigua y Barbuda'),
    ('argentina', 'Argentina'),
    ('armenia', 'Armenia'),
    ('australia', 'Australia'),
    ('austria', 'Austria'),
    ('azerbaijan', 'Azerbaiyán'),
    ('bahamas', 'Bahamas'),
    ('bahrain', 'Baréin'),
    ('bangladesh', 'Bangladesh'),
    ('barbados', 'Barbados'),
    ('belarus', 'Belarús'),
    ('belgium', 'Bélgica'),
    ('belize', 'Belice'),
    ('benin', 'Benin'),
    ('bhutan', 'Bután'),
    ('bolivia', 'Bolivia'),
    ('bosnia_and_herzegovina', 'Bosnia y Herzegovina'),
    ('botswana', 'Botswana'),
    ('brazil', 'Brasil'),
    ('brunei', 'Brunei'),
    ('bulgaria', 'Bulgaria'),
    ('burkina_faso', 'Burkina Faso'),
    ('burundi', 'Burundi'),
    ('cabo_verde', 'Cabo Verde'),
    ('cambodia', 'Camboya'),
    ('cameroon', 'Camerún'),
    ('canada', 'Canadá'),
    ('central_african_republic', 'República Centroafricana'),
    ('chad', 'Chad'),
    ('chile', 'Chile'),
    ('china', 'China'),
    ('colombia', 'Colombia'),
    ('comoros', 'Comoras'),
    ('congo', 'Congo'),
    ('costa_rica', 'Costa Rica'),
    ('cote_divoire', 'Costa de Marfil'),
    ('croatia', 'Croacia'),
    ('cuba', 'Cuba'),
    ('cyprus', 'Chipre'),
    ('czech_republic', 'República Checa'),
    ('denmark', 'Dinamarca'),
    ('djibouti', 'Yibuti'),
    ('dominica', 'Dominica'),
    ('dominican_republic', 'República Dominicana'),
    ('ecuador', 'Ecuador'),
    ('egypt', 'Egipto'),
    ('el_salvador', 'El Salvador'),
    ('equatorial_guinea', 'Guinea Ecuatorial'),
    ('eritrea', 'Eritrea'),
    ('estonia', 'Estonia'),
    ('eswatini', 'Eswatini'),
    ('ethiopia', 'Etiopía'),
    ('fiji', 'Fiji'),
    ('finland', 'Finlandia'),
    ('france', 'Francia'),
    ('gabon', 'Gabón'),
    ('gambia', 'Gambia'),
    ('georgia', 'Georgia'),
    ('germany', 'Alemania'),
    ('ghana', 'Ghana'),
    ('greece', 'Grecia'),
    ('grenada', 'Granada'),
    ('guatemala', 'Guatemala'),
    ('guinea', 'Guinea'),
    ('guinea-bissau', 'Guinea-Bisáu'),
    ('guyana', 'Guyana'),
    ('haiti', 'Haití'),
    ('honduras', 'Honduras'),
    ('hungary', 'Hungría'),
    ('iceland', 'Islandia'),
    ('india', 'India'),
    ('indonesia', 'Indonesia'),
    ('iran', 'Irán'),
    ('iraq', 'Irak'),
    ('ireland', 'Irlanda'),
    ('israel', 'Israel'),
    ('italy', 'Italia'),
    ('jamaica', 'Jamaica'),
    ('japan', 'Japón'),
    ('jordan', 'Jordania'),
    ('kazakhstan', 'Kazajistán'),
    ('kenya', 'Kenia'),
    ('kiribati', 'Kiribati'),
    ('kosovo', 'Kosovo'),
    ('kuwait', 'Kuwait'),
    ('kyrgyzstan', 'Kirguistán'),
    ('laos', 'Laos'),
    ('latvia', 'Letonia'),
    ('lebanon', 'Líbano'),
    ('lesotho', 'Lesoto'),
    ('liberia', 'Liberia'),
    ('libya', 'Libia'),
    ('liechtenstein', 'Liechtenstein'),
    ('lithuania', 'Lituania'),
    ('luxembourg', 'Luxemburgo'),
    ('madagascar', 'Madagascar'),
    ('malawi', 'Malaui'),
    ('malaysia', 'Malasia'),
    ('maldives', 'Maldivas'),
    ('mali', 'Mali'),
    ('malta', 'Malta'),
    ('marshall_islands', 'Islas Marshall'),
    ('mauritania', 'Mauritania'),
    ('mauritius', 'Mauricio'),
    ('mexico', 'México'),
    ('micronesia', 'Micronesia'),
    ('moldova', 'Moldavia'),
    ('monaco', 'Mónaco'),
    ('mongolia', 'Mongolia'),
    ('montenegro', 'Montenegro'),
    ('morocco', 'Marruecos'),
    ('mozambique', 'Mozambique'),
    ('myanmar', 'Myanmar (Birmania)'),
    ('namibia', 'Namibia'),
    ('nauru', 'Nauru'),
    ('nepal', 'Nepal'),
    ('netherlands', 'Países Bajos'),
    ('new_zealand', 'Nueva Zelanda'),
    ('nicaragua', 'Nicaragua'),
    ('niger', 'Níger'),
    ('nigeria', 'Nigeria'),
    ('north_korea', 'Corea del Norte'),
    ('north_macedonia', 'Macedonia del Norte'),
    ('norway', 'Noruega'),
    ('oman', 'Omán'),
    ('pakistan', 'Pakistán'),
    ('palau', 'Palaos'),
    ('panama', 'Panamá'),
    ('papua_new_guinea', 'Papúa Nueva Guinea'),
    ('paraguay', 'Paraguay'),
    ('peru', 'Perú'),
    ('philippines', 'Filipinas'),
    ('poland', 'Polonia'),
    ('portugal', 'Portugal'),
    ('qatar', 'Catar'),
    ('romania', 'Rumania'),
    ('russia', 'Rusia'),
    ('rwanda', 'Ruanda'),
    ('monaco', 'Mónaco'),
    ('mongolia', 'Mongolia'),
    ('montenegro', 'Montenegro'),
    ('morocco', 'Marruecos'),
    ('mozambique', 'Mozambique'),
    ('myanmar', 'Myanmar'),
    ('namibia', 'Namibia'),
    ('nauru', 'Nauru'),
    ('nepal', 'Nepal'),
    ('netherlands', 'Países Bajos'),
    ('new_zealand', 'Nueva Zelanda'),
    ('nicaragua', 'Nicaragua'),
    ('niger', 'Níger'),
    ('nigeria', 'Nigeria'),
    ('north_korea', 'Corea del Norte'),
    ('north_macedonia', 'Macedonia del Norte'),
    ('norway', 'Noruega'),
    ('oman', 'Omán'),
    ('pakistan', 'Pakistán'),
    ('palau', 'Palaos'),
    ('panama', 'Panamá'),
    ('papua_new_guinea', 'Papúa Nueva Guinea'),
    ('paraguay', 'Paraguay'),
    ('peru', 'Perú'),
    ('philippines', 'Filipinas'),
    ('poland', 'Polonia'),
    ('portugal', 'Portugal'),
    ('qatar', 'Catar'),
    ('romania', 'Rumania'),
    ('russia', 'Rusia'),
    ('rwanda', 'Ruanda'),
    ('saint_kitts_and_nevis', 'San Cristóbal y Nieves'),
    ('saint_lucia', 'Santa Lucía'),
    ('saint_vincent_and_the_grenadines', 'San Vicente y las Granadinas'),
    ('samoa', 'Samoa'),
    ('san_marino', 'San Marino'),
    ('sao_tome_and_principe', 'Santo Tomé y Príncipe'),
    ('saudi_arabia', 'Arabia Saudita'),
    ('senegal', 'Senegal'),
    ('serbia', 'Serbia'),
    ('seychelles', 'Seychelles'),
    ('sierra_leone', 'Sierra Leona'),
    ('singapore', 'Singapur'),
    ('slovakia', 'Eslovaquia'),
    ('slovenia', 'Eslovenia'),
    ('solomon_islands', 'Islas Salomón'),
    ('somalia', 'Somalia'),
    ('south_africa', 'Sudáfrica'),
    ('south_korea', 'Corea del Sur'),
    ('south_sudan', 'Sudán del Sur'),
    ('spain', 'España'),
    ('sri_lanka', 'Sri Lanka'),
    ('sudan', 'Sudán'),
    ('suriname', 'Surinam'),
    ('sweden', 'Suecia'),
    ('switzerland', 'Suiza'),
    ('syria', 'Siria'),
    ('taiwan', 'Taiwán'),
    ('tajikistan', 'Tayikistán'),
    ('tanzania', 'Tanzania'),
    ('thailand', 'Tailandia'),
    ('timor-leste', 'Timor Oriental'),
    ('togo', 'Togo'),
    ('tonga', 'Tonga'),
    ('trinidad_and_tobago', 'Trinidad y Tobago'),
    ('tunisia', 'Túnez'),
    ('turkey', 'Turquía'),
    ('turkmenistan', 'Turkmenistán'),
    ('tuvalu', 'Tuvalu'),
    ('uganda', 'Uganda'),
    ('ukraine', 'Ucrania'),
    ('united_arab_emirates', 'Emiratos Árabes Unidos'),
    ('united_kingdom', 'Reino Unido'),
    ('united_states', 'Estados Unidos'),
    ('uruguay', 'Uruguay'),
    ('uzbekistan', 'Uzbekistán'),
    ('vanuatu', 'Vanuatu'),
    ('vatican_city', 'Ciudad del Vaticano'),
    ('venezuela', 'Venezuela'),
    ('vietnam', 'Vietnam'),
    ('yemen', 'Yemen'),
    ('zambia', 'Zambia'),
    ('zimbabwe', 'Zimbabue')
]

PAISES = {
'afghanistan': 'Afganistán',
'albania': 'Albania',
'algeria': 'Argelia',
'andorra': 'Andorra',
'angola': 'Angola',
'antigua_and_barbuda': 'Antigua y Barbuda',
'argentina': 'Argentina',
'armenia': 'Armenia',
'australia': 'Australia',
'austria': 'Austria',
'azerbaijan': 'Azerbaiyán',
'bahamas': 'Bahamas',
'bahrain': 'Baréin',
'bangladesh': 'Bangladesh',
'barbados': 'Barbados',
'belarus': 'Belarús',
'belgium': 'Bélgica',
'belize': 'Belice',
'benin': 'Benin',
'bhutan': 'Bután',
'bolivia': 'Bolivia',
'bosnia_and_herzegovina': 'Bosnia y Herzegovina',
'botswana': 'Botswana',
'brazil': 'Brasil',
'brunei': 'Brunei',
'bulgaria': 'Bulgaria',
'burkina_faso': 'Burkina Faso',
'burundi': 'Burundi',
'cabo_verde': 'Cabo Verde',
'cambodia': 'Camboya',
'cameroon': 'Camerún',
'canada': 'Canadá',
'central_african_republic': 'República Centroafricana',
'chad': 'Chad',
'chile': 'Chile',
'china': 'China',
'colombia': 'Colombia',
'comoros': 'Comoras',
'congo': 'Congo',
'costa_rica': 'Costa Rica',
'cote_divoire': 'Costa de Marfil',
'croatia': 'Croacia',
'cuba': 'Cuba',
'cyprus': 'Chipre',
'czech_republic': 'República Checa',
'denmark': 'Dinamarca',
'djibouti': 'Yibuti',
'dominica': 'Dominica',
'dominican_republic': 'República Dominicana',
'ecuador': 'Ecuador',
'egypt': 'Egipto',
'el_salvador': 'El Salvador',
'equatorial_guinea': 'Guinea Ecuatorial',
'eritrea': 'Eritrea',
'estonia': 'Estonia',
'eswatini': 'Eswatini',
'ethiopia': 'Etiopía',
'fiji': 'Fiji',
'finland': 'Finlandia',
'france': 'Francia',
'gabon': 'Gabón',
'gambia': 'Gambia',
'georgia': 'Georgia',
'germany': 'Alemania',
'ghana': 'Ghana',
'greece': 'Grecia',
'grenada': 'Granada',
'guatemala': 'Guatemala',
'guinea': 'Guinea',
'guinea_bissau': 'Guinea-Bissau',
'guyana': 'Guyana',
'haiti': 'Haití',
'honduras': 'Honduras',
'hungary': 'Hungría',
'iceland': 'Islandia',
'india': 'India',
'indonesia': 'Indonesia',
'iran': 'Irán',
'iraq': 'Irak',
'ireland': 'Irlanda',
'israel': 'Israel',
'italy': 'Italia',
'jamaica': 'Jamaica',
'japan': 'Japón',
'jordan': 'Jordania',
'kazakhstan': 'Kazajistán',
'kenya': 'Kenia',
'kiribati': 'Kiribati',
'kosovo': 'Kosovo',
'kuwait': 'Kuwait',
'kyrgyzstan': 'Kirguistán',
'laos': 'Laos',
'latvia': 'Letonia',
'lebanon': 'Líbano',
'lesotho': 'Lesotho',
'liberia': 'Liberia',
'libya': 'Libia',
'liechtenstein': 'Liechtenstein',
'lithuania': 'Lituania',
'luxembourg': 'Luxemburgo',
'madagascar': 'Madagascar',
'malawi': 'Malawi',
'malaysia': 'Malasia',
'maldives': 'Maldivas',
'mali': 'Mali',
'malta': 'Malta',
'marshall_islands': 'Islas Marshall',
'mauritania': 'Mauritania',
'mauritius': 'Mauricio',
'mexico': 'México',
'micronesia': 'Micronesia',
'moldova': 'Moldavia',
'monaco': 'Mónaco',
'mongolia': 'Mongolia',
'montenegro': 'Montenegro',
'morocco': 'Marruecos',
'mozambique': 'Mozambique',
'myanmar': 'Myanmar',
'namibia': 'Namibia',
'nauru': 'Nauru',
'nepal': 'Nepal',

luchadores/forms.py
from django import forms
from .models import Luchador

DATE_INPUT_FORMATS = ["%d.%m.%Y"]


class LuchadorForm(forms.ModelForm):
    nacimiento = forms.DateField(widget=forms.SelectDateWidget(
        attrs={'class': 'form-control datepicker_input'}, years=[y for y in range(1950,2023)]))
    class Meta:
        model = Luchador
        fields = ['nombre', 'apellidos', 'peso', 'altura', 'pais', 'guardia', 'alcance', 'nacimiento']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
            'peso': forms.NumberInput(attrs={'class': 'form-control'}),
            'altura': forms.NumberInput(attrs={'class': 'form-control'}),
            'pais': forms.Select(attrs={'class': 'form-control'}),
            'guardia': forms.Select(attrs={'class': 'form-control'}),
            'alcance': forms.NumberInput(attrs={'class': 'form-control'}),
            'nacimiento': forms.DateInput(attrs={'class': 'form-control datepicker_input'}),
        }

luchadores/views.py
from pyexpat.errors import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin

from luchadores.forms import LuchadorForm

from .models import Luchador, PAISES
from combates.models import Combate
from bases.views import actualizar_registros

# Create your views here.

class luchadoresList(LoginRequiredMixin, generic.ListView):
    model = Luchador
    template_name = 'luchadores/luchadoresList.html'
    login_url = 'bases:login'
    actualizar_registros()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['luchadores'] = Luchador.objects.filter(creator = self.request.user).order_by("-victorias", "derrotas")
        return context

class LuchadorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Luchador
    form_class = LuchadorForm
    success_url = reverse_lazy('luchadores:luchadores-list')
    template_name = 'luchadores/luchadoresForm.html'
    login_url = 'bases:login'
    actualizar_registros()

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.nacionalidad = PAISES[form.instance.pais]
        return super().form_valid(form)


class LuchadorEditView(LoginRequiredMixin, generic.UpdateView):
    model=Luchador
    form_class = LuchadorForm
    template_name = 'luchadores/luchadoresForm.html'
    context_object_name="obj"
    login_url = 'bases:login'
    success_url=reverse_lazy("luchadores:luchadores-list")
    actualizar_registros()
    
    def form_valid(self, form):
        form.instance.nacionalidad = PAISES[form.instance.pais]
        return super().form_valid(form)
        
    
class LuchadorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Luchador
    template_name = 'luchadores/luchadoresDelete.html'
    context_object_name = "obj"
    login_url = 'bases:login'
    success_url=reverse_lazy("luchadores:luchadores-list")
    actualizar_registros()
    
    
class LuchadorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Luchador
    login_url = 'bases:login'
    template_name = 'luchadores/luchadoresDetail.html'
    actualizar_registros()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        combates = Combate.objects.filter(Q(luchador_azul__id=self.get_object().id) | Q(luchador_rojo__id=self.get_object().id))
        context['combates'] =combates
        
        context["balanceText"] = ['Victorias', 'Empates', 'Derrotas']
        context['balance'] = [self.get_object().victorias, self.get_object().empates, self.get_object().derrotas]
        
        context["golpesText"] = ['Acertados', 'Evitados', 'Fallados', 'Encajados']
        context['golpes'] = [self.get_object().golpes_acertados, self.get_object().golpes_evitados, self.get_object().golpes_fallados, self.get_object().golpes_encajados]
        
        context["tiposGolpesText"] = ['Directos', 'Crochets', 'Ganchos']
        context['tiposGolpes'] = [self.get_object().directos, self.get_object().crochets, self.get_object().ganchos]
        return context
    

luchadores/templates/luchadores/luchadoresDelete.html
{% extends 'base/base.html' %}

{% block menu %}{% endblock menu %}

{% block content %}
{% load static %}


<div class= "row mt-5">
    <div class= "col-lg-8 col-md-10 col-sm-12 m-auto card o-hidden border-0 shadow-lg p-5 my-5">
    <h3 class="loginTitle mb-1">¿Estás seguro que deseas eliminar a {{ object }}?</h3>
    <p class=" m-4 mt-0 text-dark">Eliminarás también todos los combates en los que ha participado y por tanto las estadísticas de sus contrincantes en éstos.</p>
    <form method="post">
        {% csrf_token %}
        <div class="row">
                <input type="submit" class="btn btn-danger col-lg-5 col-md-7 col-sm-7 m-auto mt-1" value="Eliminar">
                <a class="btn btn-dark col-lg-5 col-md-7 col-sm-7 m-auto mt-1" href="{% url 'luchadores:luchadores-list'%}">Volver</a>
        </div>
      </form>
  </div>
  </div>
{% endblock content %}

{% block footer %}{% endblock footer %}

{% block javascript %}
<script>
    window.addEventListener("scroll", function() {
        var menu = document.querySelector(".menu");
        var backgrounds = document.querySelectorAll(".background");

        var scrolled = false;
        for (var i = 0; i < backgrounds.length; i++) {
            var rect = backgrounds[i].getBoundingClientRect();
            if (rect.top <= menu.offsetHeight && rect.bottom >= menu.offsetHeight) {
                scrolled = true;
                break;
            }
        }

        if (scrolled) {
            menu.classList.remove("scrolled");
        } else {
            menu.classList.add("scrolled");
        }
    });

    $(document).ready(function() {
        $(".menu").fadeIn(2000);
    });
</script>
{% endblock javascript %}

luchadores/templates/luchadores/luchadoresForm.html
{% extends 'base/base.html' %}

{% block menu %}{% endblock menu %}

{% block content %}
{% load static %}



<div class= "row bgt">
    <div class= "col-lg-8 col-md-12 col-sm-12 offset-lg-2 offset-md-0 offset-sm-0 card o-hidden border-0 shadow-lg p-5 my-5">
        {% if obj %}
        <h1 class="longtitle mt-3">Editar luchador</h1>
        {% else %}
        <h1 class="longtitle mt-3">Crear nuevo luchador</h1>
        {% endif %}
        <form method="post" class="col-8 offset-2 mt-5">
            {% csrf_token %}
            <div class="col-12">
                {% for field in form %}
                <div class="form-group mt-3 {% if not field.errors %}was-validated {% else %} was-invalid {% endif %} ">
                    {{ field.label_tag }}
                    <div class="mt-1">{{ field }}</div>
                    {% if field.errors %}
                    <div div class = "form_error">
                        {{ field.errors }}
                    </div>
                {% endif %}
                </div>
            
        {% endfor %}
            </div>
        
            {% if obj %}
            <div class="mt-5 col-12 text-center">
                <button type="submit" class="btn btn-danger col-lg-4 col-md-8 col-sm-8 mt-2 m-auto">Editar</button>
                <a href="{% url 'luchadores:luchadores-list' %}" class="btn btn-dark col-lg-4 col-md-8 col-sm-8 mt-2 m-auto">Volver</a>
            </div>
            {% else %}
            <div class="mt-5 col-12 text-center">
                <button type="submit" class="btn btn-danger col-lg-4 col-md-8 col-sm-8 mt-2 m-auto">Crear</button>
                <a href="{% url 'luchadores:luchadores-list' %}" class="btn btn-dark col-lg-4 col-md-8 col-sm-8 mt-2 m-auto">Volver</a>
            </div>
            
            {% endif %}
            
        </form>
</div>

{% endblock content %}

{% block javascript %}
<script>
    window.addEventListener("scroll", function() {
        var menu = document.querySelector(".menu");
        var backgrounds = document.querySelectorAll(".background");

        var scrolled = false;
        for (var i = 0; i < backgrounds.length; i++) {
            var rect = backgrounds[i].getBoundingClientRect();
            if (rect.top <= menu.offsetHeight && rect.bottom >= menu.offsetHeight) {
                scrolled = true;
                break;
            }
        }

        if (scrolled) {
            menu.classList.remove("scrolled");
        } else {
            menu.classList.add("scrolled");
        }
    });

    $(document).ready(function() {
        $(".menu").fadeIn(2000);
    });
</script>
{% endblock javascript %}

luchadores/templates/luchadores/luchadoresList.html
{% extends 'base/base.html' %}

{% block menu %}
        <div class="row">
            <div class="menu fixed-top col-lg-6 col-md-10 col-sm-10 mt-4 m-auto">
                <div class="row h-100">
                    <a class="col-lg-4 col-md-12 col-sm-12 pt-2 pb-2 text-center menuLink2" href="{% url 'luchadores:luchadores_create' %}">NUEVO LUCHADOR</a>
                    <a class="col-lg-4 col-md-12 col-sm-12 text-center mma menuLink1" href="{% url 'bases:home' %}">my ufc</a>
                    <a class="col-lg-4 col-md-12 col-sm-12 pt-2 pb-2 text-center menuLink2" href="{% url 'combates:combates-list' %}">COMBATES</a>
                </div>
            </div>
        </div>
        {% endblock menu %}

{% block content %}
{% load static %}


<div class="background background4 row">
    
</div>


<div class= "row">
<div class= "col-lg-10 col-md-12 col-sm-12 offset-lg-1 offset-md-0 offset-sm-0 card o-hidden border-0 shadow-lg p-5 my-5">
    
{% comment %} <h1 class="text-center mb-5">LISTADO DE LUCHADORES</h1> {% endcomment %}


<table class="info">
    <h3 class=" text-center mb-3">LISTADO DE LUCHADORES</h3>
    <thead>
    <tr>
        <th scope="col">Nombre</th>
        {% comment %} <th>Edad</th> {% endcomment %}
        <th scope="col">Apellidos</th>
        <th scope="col">Peso</th>
        <th scope="col">Altura</th>
        <th scope="col">Alcance</th>
        <th scope="col">Victorias</th>
        <th scope="col">Empates</th>
        <th scope="col">Derrotas</th>
        <th scope="col">Acciones</th>
    </tr>
    </thead>
    <tbody>
        {% for luchador in luchadores %}
    <tr>
        <td>{{ luchador.nombre }}</td>
            {% comment %} <td>{{ luchador.edad }}</td> {% endcomment %}
            <td>{{ luchador.apellidos }}</td>
            <td>{{ luchador.peso }}</td>
            <td>{{ luchador.altura }}</td>
            <td>{{ luchador.alcance }}</td>
            <td>{{ luchador.victorias }}</td>
            <td>{{ luchador.empates }}</td>
            <td>{{ luchador.derrotas }}</td>
            <td>
            <a href="{% url 'luchadores:luchadores_detail' luchador.id %}" class="text-dark m-1"><ion-icon class="icono" name="information-outline"></ion-icon></a>
            <a href="{% url 'luchadores:luchadores_edit' luchador.id %}" class="text-dark m-1"><ion-icon class="icono" name="create-outline"></ion-icon></a>
            <a href="{% url 'luchadores:luchadores_delete' luchador.id %}" class="text-danger m-1"><ion-icon class="icono" name="trash-outline"></ion-icon></a>
            </td>
    </tr>
    {% empty %}
        <tr>
            <td colspan="9">No hay luchadores registrados.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>





</div>
</div>





{% endblock content %}

{% block javascript %}
<script>
    window.addEventListener("scroll", function() {
        var menu = document.querySelector(".menu");
        var backgrounds = document.querySelectorAll(".background");

        var scrolled = false;
        for (var i = 0; i < backgrounds.length; i++) {
            var rect = backgrounds[i].getBoundingClientRect();
            if (rect.top <= menu.offsetHeight && rect.bottom >= menu.offsetHeight) {
                scrolled = true;
                break;
            }
        }

        if (scrolled) {
            menu.classList.remove("scrolled");
        } else {
            menu.classList.add("scrolled");
        }
    });

    $(document).ready(function() {
        $(".menu").fadeIn(2000);
    });
</script>
{% endblock javascript %}