MyUFC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('luchadores/', include(('luchadores.urls', 'luchadores'), namespace='luchadores')),
    path('combates/', include(('combates.urls', 'combates'), namespace='combates')),
    
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from bases.views import Home

urlpatterns = [
    path('', Home.as_view(), name='home'),
    
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

combates/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from combates.views import CombateListView, CombateEditView, CombateDeleteView, CombateCreateView, CombateDetailView

urlpatterns = [
    path('', CombateListView.as_view(), name='combates-list'),
    path('new', CombateCreateView.as_view(), name = 'combates_create'),
    path('edit/<uuid:pk>/', CombateEditView.as_view(), name = 'combates_edit'),
    path('delete/<uuid:pk>/', CombateDeleteView.as_view(), name='combates_delete'),
    path('detail/<uuid:pk>/', CombateDetailView.as_view(), name='combates_detail'),
]

luchadores/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from luchadores.views import luchadoresList, LuchadorCreateView, LuchadorEditView, LuchadorDeleteView, LuchadorDetailView

urlpatterns = [
    path('', luchadoresList.as_view(), name='luchadores-list'),
    path('new', LuchadorCreateView.as_view(), name = 'luchadores_create'),
    path('edit/<uuid:pk>/', LuchadorEditView.as_view(), name = 'luchadores_edit'),
    path('delete/<uuid:pk>/', LuchadorDeleteView.as_view(), name='luchadores_delete'),
    path('detail/<uuid:pk>/', LuchadorDetailView.as_view(), name='luchadores_detail'),
]

combates/models.py
from django.db import models

from bases.models import BaseModel
from luchadores.models import Luchador


RESULTADOS_CHOICES = [
        ('Rojo', 'Rojo'),
        ('Empate', 'Empate'),
        ('Azul', 'Azul'),
    ]

# Create your models here.

class Combate(BaseModel):
    luchador_rojo = models.ForeignKey(Luchador, on_delete=models.CASCADE, related_name='combates_rojo')
    luchador_azul = models.ForeignKey(Luchador, on_delete=models.CASCADE, related_name='combates_azul')
    fecha = models.DateField()
    round_max = models.PositiveIntegerField()
    resultado = models.CharField(choices=RESULTADOS_CHOICES)
    golpes_rojo = models.PositiveIntegerField()
    golpes_acertados_rojo = models.PositiveIntegerField()
    golpes_fallados_rojo = models.PositiveIntegerField()
    golpes_directos_rojo = models.PositiveIntegerField()
    golpes_crochet_rojo = models.PositiveIntegerField()
    golpes_gancho_rojo = models.PositiveIntegerField()
    golpes_azul = models.PositiveIntegerField()
    golpes_acertados_azul = models.PositiveIntegerField()
    golpes_fallados_azul = models.PositiveIntegerField()
    golpes_directos_azul = models.PositiveIntegerField()
    golpes_crochet_azul = models.PositiveIntegerField()
    golpes_gancho_azul = models.PositiveIntegerField()

combates/forms.py
from django import forms
from .models import Combate
from luchadores.models import Luchador

class CombateForm(forms.ModelForm):
    fecha = forms.DateField(widget=forms.SelectDateWidget(
        attrs={'class': 'form-control datepicker_input'}, years=[y for y in range(1950,2023)]))
    class Meta:
        model = Combate
        fields = ['luchador_rojo', 'luchador_azul', 'fecha', 'round_max', 'resultado', 
                    'golpes_acertados_rojo', 
                    'golpes_directos_rojo', 'golpes_crochet_rojo', 'golpes_gancho_rojo',
                    'golpes_acertados_azul',
                    'golpes_directos_azul', 'golpes_crochet_azul', 'golpes_gancho_azul']
        
        widgets = {
            'luchador_rojo': forms.Select(attrs={'class': 'form-control'}),
            'luchador_azul': forms.Select(attrs={'class': 'form-control'}),
            'round_max': forms.NumberInput(attrs={'class': 'form-control'}),
            'resultado': forms.Select(attrs={'class': 'form-control'}),
            'golpes_acertados_rojo': forms.NumberInput(attrs={'class': 'form-control'}),
            'golpes_directos_rojo': forms.NumberInput(attrs={'class': 'form-control'}),
            'golpes_crochet_rojo': forms.NumberInput(attrs={'class': 'form-control'}),
            'golpes_gancho_rojo': forms.NumberInput(attrs={'class': 'form-control'}),
            'golpes_acertados_azul': forms.NumberInput(attrs={'class': 'form-control'}),
            'golpes_directos_azul': forms.NumberInput(attrs={'class': 'form-control'}),
            'golpes_crochet_azul': forms.NumberInput(attrs={'class': 'form-control'}),
            'golpes_gancho_azul': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        
        labels = {
            'luchador_rojo': 'Luchador Rojo',
            'luchador_azul': 'Luchador Azul',
            'round_max': 'Rondas Totales',
            'resultado': 'Ganador del Combate',
            'golpes_acertados_rojo': 'Golpes Acertados Rojo',
            'golpes_directos_rojo': 'Golpes Directos Rojo',
            'golpes_crochet_rojo': 'Golpes Crochet Rojo',
            'golpes_gancho_rojo': 'Golpes Gancho Rojo',
            'golpes_acertados_azul': 'Golpes Acertados Azul',
            'golpes_directos_azul': 'Golpes Directos Azul',
            'golpes_crochet_azul': 'Golpes Crochet Azul',
            'golpes_gancho_azul': 'Golpes Gancho Azul',
        }
    
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            luchadores = Luchador.objects.filter(creator=user)
            self.fields['luchador_rojo'].queryset = luchadores
            self.fields['luchador_azul'].queryset = luchadores
            
    def clean_round_max(self):
        round_max = self.cleaned_data['round_max']
        if round_max > 3:
            raise forms.ValidationError('El máximo de rondas es de 3', code='invalid_round_max')
        return round_max
    
    def clean_golpes_azul(self):
        golpes_acertados_azul = self.cleaned_data['golpes_acertados_azul']
        golpes = self.cleaned_data['golpes_directos_azul'] + self.cleaned_data['golpes_crochet_azul'] + self.cleaned_data['golpes_gancho_azul']
        
        if  golpes_acertados_azul > golpes:
            raise forms.ValidationError('No puede haber más golpes acertados que golpes totales.', code='invalid_kicks')

combates/views.py
from pyexpat.errors import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CombateForm

from .models import Combate

from bases.views import actualizar_registros

# Create your views here.

class CombateListView(LoginRequiredMixin, generic.ListView):
    model = Combate
    template_name = 'combates/combatesList.html'
    login_url = 'bases:login'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        actualizar_registros()
        context['combates'] = Combate.objects.filter(creator = self.request.user).order_by("-fecha")
        return context

class CombateCreateView(LoginRequiredMixin, generic.CreateView):
    model = Combate
    form_class = CombateForm
    success_url = reverse_lazy('combates:combates-list')
    template_name = 'combates/combatesForm.html'
    login_url = 'bases:login'
    actualizar_registros()

    def form_valid(self, form):
        form.instance.creator = self.request.user
        
        golpes_rojo = form.instance.golpes_directos_rojo + form.instance.golpes_crochet_rojo + form.instance.golpes_gancho_rojo
        golpes_azul = form.instance.golpes_directos_azul + form.instance.golpes_crochet_azul + form.instance.golpes_gancho_azul
        form.instance.golpes_rojo = form.instance.golpes_directos_rojo + form.instance.golpes_crochet_rojo + form.instance.golpes_gancho_rojo
        form.instance.golpes_azul = form.instance.golpes_directos_azul + form.instance.golpes_crochet_azul + form.instance.golpes_gancho_azul
        
        form.instance.golpes_fallados_rojo = golpes_rojo - form.instance.golpes_acertados_rojo
        form.instance.golpes_fallados_azul = golpes_azul - form.instance.golpes_acertados_azul
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super(CombateCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class CombateEditView(LoginRequiredMixin, generic.UpdateView):
    model=Combate
    form_class = CombateForm
    template_name = 'combates/combatesForm.html'
    context_object_name="obj"
    login_url = 'bases:login'
    success_url=reverse_lazy("combates:combates-list")
    actualizar_registros()
    
    def form_valid(self, form):
        golpes_rojo = form.instance.golpes_directos_rojo + form.instance.golpes_crochet_rojo + form.instance.golpes_gancho_rojo
        golpes_azul = form.instance.golpes_directos_azul + form.instance.golpes_crochet_azul + form.instance.golpes_gancho_azul
        
        form.instance.golpes_rojo = form.instance.golpes_directos_rojo + form.instance.golpes_crochet_rojo + form.instance.golpes_gancho_rojo
        form.instance.golpes_azul = form.instance.golpes_directos_azul + form.instance.golpes_crochet_azul + form.instance.golpes_gancho_azul
        
        form.instance.golpes_fallados_rojo = golpes_rojo - form.instance.golpes_acertados_rojo
        form.instance.golpes_fallados_azul = golpes_azul - form.instance.golpes_acertados_azul
        return super().form_valid(form)
        
    
class CombateDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Combate
    template_name = 'combates/combatesDelete.html'
    context_object_name = "obj"
    login_url = 'bases:login'
    success_url=reverse_lazy("combates:combates-list")
    actualizar_registros()
    
    
class CombateDetailView(LoginRequiredMixin, generic.DetailView):
    model = Combate
    login_url = 'bases:login'
    template_name = 'combates/combatesDetail.html'
    actualizar_registros()

combates/templates/combates/combatesDelete.html
{% extends 'base/base.html' %}

{% block menu %}{% endblock menu %}

{% block content %}
{% load static %}


<div class= "row mt-5">
    <div class= "col-lg-8 col-md-10 col-sm-12 m-auto card o-hidden border-0 shadow-lg p-5 my-5">
    <h3 class="loginTitle mb-1">¿Estás seguro que deseas eliminar este combate?</h3>
    <p class=" m-4 mt-0 text-dark">El combate se dió el {{object.fecha}} entre {{object.luchador_rojo}} y {{object.luchador_azul}}.</p>
    <form method="post">
        {% csrf_token %}
        <div class="row">
                <input type="submit" class="btn btn-danger col-lg-5 col-md-7 col-sm-7 m-auto mt-1" value="Eliminar">
                <a class="btn btn-dark col-lg-5 col-md-7 col-sm-7 m-auto mt-1" href="{% url 'combates:combates-list'%}">Volver</a>
        </div>
      </form>
  </div>
  </div>
{% endblock content %}

{% block footer %}{% endblock footer %}

{% block javascript %}
<script>
    window.addEventListener("scroll", function() {
        var menu = document.querySelector(".menu");
        var backgrounds = document.querySelectorAll(".background");

        var scrolled = false;
        for (var i = 0; i < backgrounds.length; i++) {
            var rect = backgrounds[i].getBoundingClientRect();
            if (rect.top <= menu.offsetHeight && rect.bottom >= menu.offsetHeight) {
                scrolled = true;
                break;
            }
        }

        if (scrolled) {
            menu.classList.remove("scrolled");
        } else {
            menu.classList.add("scrolled");
        }
    });

    $(document).ready(function() {
        $(".menu").fadeIn(2000);
    });
</script>
{% endblock javascript %}

combates/templates/combates/combatesDetail.html
{% extends 'base/base.html' %}

{% block menu %}{% endblock menu %}

{% block content %}
{% load static %}



<div class= "row bgt">
    <div class= "col-lg-8 col-md-12 col-sm-12 offset-lg-2 offset-md-0 offset-sm-0 card o-hidden border-0 shadow-lg p-5 my-5">
        <h1 class = "mma mb-5">{{ object.luchador_rojo|lower }} - {{ object.luchador_azul|lower }}</h1>
        <div class="col-10 m-auto">
            <ul class="list-group list-group-flush">
                <li class="list-group-item m-2"><b>Luchador rojo:</b> <a class="link" href="{% url 'luchadores:luchadores_detail' object.luchador_rojo.id %}">{{ object.luchador_rojo }}</a></li>
                <li class="list-group-item m-2"><b>Luchador azul:</b> <a class="link" href="{% url 'luchadores:luchadores_detail' object.luchador_azul.id %}">{{ object.luchador_azul }}</a> </li>
                <li class="list-group-item m-2"><b>Fecha:</b> {{ object.fecha }} </li>
                <li class="list-group-item m-2"><b>Rondas:</b> {{ object.round_max }} </li>
                <li class="list-group-item m-2"><b>Ganador:</b> {{ object.resultado }}</li>
            </ul>
        </div>
        {% comment %} <p>Fecha de nacimiento: {{ object.nacimiento }}</p>
  <p>Peso: {{ object.peso }} kg</p>
  <p>Altura: {{ object.altura }} m</p>
  <p>Alcance: {{ object.alcance }} m</p>
  <p>Victorias: {{ object.victorias }}</p>
  <p>{{ object. }}</p>
  <p>Derrotas: {{ object.derrotas }}</p> {% endcomment %}
  <!-- agregar más información del luchador aquí -->
  <div class="mt-5 col-12 text-center">
    <a href="{% url 'combates:combates-list' %}" class="btn btn-dark col-lg-4 col-md-8 col-sm-8 mt-2 m-auto">Volver</a>
</div>
</div>

{% endblock content %}

{% block javascript %}
<script>
    window.addEventListener("scroll", function() {
        var menu = document.querySelector(".menu");
        var backgrounds = document.querySelectorAll(".background");

        var scrolled = false;
        for (var i = 0; i < backgrounds.length; i++) {
            var rect = backgrounds[i].getBoundingClientRect();
            if (rect.top <= menu.offsetHeight && rect.bottom >= menu.offsetHeight) {
                scrolled = true;
                break;
            }
        }

        if (scrolled) {
            menu.classList.remove("scrolled");
        } else {
            menu.classList.add("scrolled");
        }
    });

    $(document).ready(function() {
        $(".menu").fadeIn(2000);
    });
</script>
{% endblock javascript %}

combates/templates/combates/combatesForm.html
{% extends 'base/base.html' %}

{% block menu %}{% endblock menu %}

{% block content %}
{% load static %}



<div class= "row bgt">
    <div class= "col-lg-8 col-md-12 col-sm-12 offset-lg-2 offset-md-0 offset-sm-0 card o-hidden border-0 shadow-lg p-5 my-5">
        {% if obj %}
        <h1 class="longtitle mt-3">Editar combate</h1>
        {% else %}
        <h1 class="longtitle mt-3">Crear nuevo combate</h1>
        {% endif %}
        <form method="post" class=" col-8 offset-2 mt-5">
            {% csrf_token %}
            <div class="col-12">
                {% for field in form %}
            <div class="form-group mt-3 {% if not field.errors %}was-validated {% else %} was-invalid {% endif %} ">
                {{ field.label_tag }}
                <div class="mt-1">{{ field }}</div>
                {% if field.errors %}
                <div div class = "form_error">
                    {{ field.errors }}
                </div>
            {% endif %}
            </div>
        {% endfor %}
            </div>
        
            {% if obj %}
            <div class="mt-5 col-12 text-center">
                <button type="submit" class="btn btn-danger col-lg-4 col-md-8 col-sm-8 mt-2 m-auto">Editar</button>
                <a href="{% url 'combates:combates-list' %}" class="btn btn-dark col-lg-4 col-md-8 col-sm-8 mt-2 m-auto">Volver</a>
            </div>
            {% else %}
            <div class="mt-5 col-12 text-center">
                <button type="submit" class="btn btn-danger col-lg-4 col-md-8 col-sm-8 mt-2 m-auto">Crear</button>
                <a href="{% url 'combates:combates-list' %}" class="btn btn-dark col-lg-4 col-md-8 col-sm-8 mt-2 m-auto">Volver</a>
            </div>
            
            {% endif %}
            
        </form>
</div>

{% endblock content %}

{% block javascript %}
<script>
    window.addEventListener("scroll", function() {
        var menu = document.querySelector(".menu");
        var backgrounds = document.querySelectorAll(".background");

        var scrolled = false;
        for (var i = 0; i < backgrounds.length; i++) {
            var rect = backgrounds[i].getBoundingClientRect();
            if (rect.top <= menu.offsetHeight && rect.bottom >= menu.offsetHeight) {
                scrolled = true;
                break;
            }
        }

        if (scrolled) {
            menu.classList.remove("scrolled");
        } else {
            menu.classList.add("scrolled");
        }
    });

    $(document).ready(function() {
        $(".menu").fadeIn(2000);
    });
</script>
{% endblock javascript %}

combates/templates/combates/combatesList.html
{% extends 'base/base.html' %}

{% block menu %}
        <div class="row">
            <div class="menu fixed-top col-lg-6 col-md-10 col-sm-10 mt-4 m-auto">
                <div class="row h-100">
                    <a class="col-lg-4 col-md-12 col-sm-12 pt-2 pb-2 text-center menuLink2" href="{% url 'luchadores:luchadores-list' %}">LUCHADORES</a>
                    <a class="col-lg-4 col-md-12 col-sm-12 text-center mma menuLink1" href="{% url 'bases:home' %}">my ufc</a>
                    <a class="col-lg-4 col-md-12 col-sm-12 pt-2 pb-2 text-center menuLink2" href="{% url 'combates:combates_create' %}">NUEVO COMBATE</a>
                </div>
            </div>
        </div>
        {% endblock menu %}

{% block content %}
{% load static %}


<div class="background background5 row">
    
</div>


<div class= "row">
<div class= "col-lg-10 col-md-12 col-sm-12 offset-lg-1 offset-md-0 offset-sm-0 card o-hidden border-0 shadow-lg p-5 my-5">


<table class="info">
    <h3 class=" text-center mb-3">LISTADO DE COMBATES</h3>
    <thead>
    <tr>
        <th scope="col">LUCHADOR ROJO</th>
        <th scope="col">LUCHADOR AZUL</th>
        <th scope="col">FECHA</th>
        <th scope="col">ROUNDS</th>
        <th scope="col">RESULTADO</th>
        <th scope="col">ACCIONES</th>
    </tr>
    </thead>
    <tbody>
        {% for combate in combates %}
    <tr>
            <td>{{ combate.luchador_rojo }}</td>
            <td>{{ combate.luchador_azul }}</td>
            <td>{{ combate.fecha }}</td>
            <td>{{ combate.round_max }}</td>
            <td>{{ combate.resultado }}</td>
            <td>
            <a href="{% url 'combates:combates_detail' combate.id %}" class="text-dark m-1"><ion-icon class="icono" name="information-outline"></ion-icon></a>
            <a href="{% url 'combates:combates_edit' combate.id %}" class="text-dark m-1"><ion-icon class="icono" name="create-outline"></ion-icon></a>
            <a href="{% url 'combates:combates_delete' combate.id %}" class="text-danger m-1"><ion-icon class="icono" name="trash-outline"></ion-icon></a>
            </td>
    </tr>
    {% empty %}
        <tr>
            <td colspan="6">No hay combates registrados.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>





</div>
</div>





{% endblock content %}

{% block javascript %}
<script>
    window.addEventListener("scroll", function() {
        var menu = document.querySelector(".menu");
        var backgrounds = document.querySelectorAll(".background");

        var scrolled = false;
        for (var i = 0; i < backgrounds.length; i++) {
            var rect = backgrounds[i].getBoundingClientRect();
            if (rect.top <= menu.offsetHeight && rect.bottom >= menu.offsetHeight) {
                scrolled = true;
                break;
            }
        }

        if (scrolled) {
            menu.classList.remove("scrolled");
        } else {
            menu.classList.add("scrolled");
        }
    });

    $(document).ready(function() {
        $(".menu").fadeIn(2000);
    });
</script>
{% endblock javascript %}